spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: 229149
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
